# Alembic Configuration

# Path to migration scripts
sqlalchemy.url = postgresql://user:password@localhost:5432/pandacafe

script_location = alembic

# template settings
file_template = %%(rev)s_%%(slug)s

date_format = %Y%m%d_%H%M%S

# Migration environment settings
sqlalchemy.echo = false
sqlalchemy.future = true
compare_server_default = true
compare_type = true
